/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#007AFF',
        'primary-dark': '#0066CC',
        secondary: '#5856D6',
        'secondary-dark': '#4846C2',
        success: '#34C759',
        warning: '#FF9500',
        danger: '#FF3B30',
        'danger-dark': '#E63629',
        background: '#FFFFFF',
        surface: '#F2F2F7',
        card: '#FFFFFF',
        text: '#000000',
        'text-secondary': '#3C3C43',
        'text-tertiary': '#8E8E93',
        border: '#C6C6C8',
        icon: '#3C3C43',
        notification: '#FF3B30',
        dark: {
          background: '#000000',
          surface: '#1C1C1E',
          card: '#1C1C1E',
          text: '#FFFFFF',
          'text-secondary': '#EBEBF5',
          'text-tertiary': '#8E8E93',
          primary: '#0A84FF',
          secondary: '#5E5CE6',
          success: '#30D158',
          warning: '#FF9F0A',
          danger: '#FF453A',
          border: '#38383A',
          icon: '#EBEBF5',
          notification: '#FF453A',
        },
      },
    },
  },
};
